"""add_journal_to_entries"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39300e9056c8'
down_revision = 'eca390d20413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('journal', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'journal')
    # ### end Alembic commands ###
