"""add_reminder_time_to_habits

Revision ID: a1b2c3d4e5f6
Revises: 39300e9056c8
Create Date: 2024-11-17 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '39300e9056c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('reminder_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'reminder_time')
    # ### end Alembic commands ###

