"""add user password field"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'eca390d20413'
down_revision = 'c3e3db09d175'
branch_labels = None
depends_on = None


def upgrade():
    # Get the connection to check database type
    bind = op.get_bind()
    inspector = inspect(bind)
    is_sqlite = bind.dialect.name == 'sqlite'
    
    # Add hashed_password column (works on all databases)
    # Check if column already exists (in case migration was partially applied)
    columns = [col['name'] for col in inspector.get_columns('users')]
    if 'hashed_password' not in columns:
        op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    
    # For SQLite, we skip ALTER COLUMN operations as SQLite doesn't support them
    # and the columns already work fine without explicit NOT NULL constraints
    if not is_sqlite:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('entries', 'habit_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        op.alter_column('entries', 'date',
                   existing_type=sa.DATE(),
                   nullable=False)
        op.alter_column('habits', 'user_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        op.alter_column('habits', 'name',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        op.alter_column('habits', 'goal_type',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        # ### end Alembic commands ###


def downgrade():
    # Get the connection to check database type
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    
    # Drop hashed_password column (works on all databases)
    op.drop_column('users', 'hashed_password')
    
    # For SQLite, we skip ALTER COLUMN operations
    if not is_sqlite:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('habits', 'goal_type',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        op.alter_column('habits', 'name',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        op.alter_column('habits', 'user_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        op.alter_column('entries', 'date',
                   existing_type=sa.DATE(),
                   nullable=True)
        op.alter_column('entries', 'habit_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        # ### end Alembic commands ###
