"""add user password field"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca390d20413'
down_revision = 'c3e3db09d175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite batch mode ###
    with op.batch_alter_table('entries') as batch_op:
        batch_op.alter_column('habit_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('date',
                   existing_type=sa.DATE(),
                   nullable=False)

    with op.batch_alter_table('habits') as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('goal_type',
                   existing_type=sa.VARCHAR(),
                   nullable=False)

    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite batch mode ###
    op.drop_column('users', 'hashed_password')

    with op.batch_alter_table('habits') as batch_op:
        batch_op.alter_column('goal_type',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)

    with op.batch_alter_table('entries') as batch_op:
        batch_op.alter_column('date',
                   existing_type=sa.DATE(),
                   nullable=True)
        batch_op.alter_column('habit_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###
