"""add user password field"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca390d20413'
down_revision = 'c3e3db09d175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'habit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entries', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('habits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('habits', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('habits', 'goal_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.alter_column('habits', 'goal_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('habits', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('habits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entries', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('entries', 'habit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
