from collections.abc import Iterable
from datetime import date, time
from typing import Protocol, Optional, List, Union

from app.models import Category, Entry, Habit

# Sentinel to indicate reminder_time was not provided in update
_REMINDER_TIME_NOT_PROVIDED = object()


class HabitRepository(Protocol):
    def create(self, user_id: int, name: str, goal_type: str, reminder_time: Optional[time] = None) -> Habit: ...
    def get(self, habit_id: int) -> Optional[Habit]: ...
    def list_by_user(self, user_id: int) -> List[Habit]: ...
    def list_by_user_and_category(self, user_id: int, category_id: int) -> List[Habit]: ...
    def exists_name(self, user_id: int, name: str) -> bool: ...
    def update(self, habit_id: int, name: Optional[str], goal_type: Optional[str], reminder_time: Union[Optional[time], object] = _REMINDER_TIME_NOT_PROVIDED) -> Optional[Habit]: ...
    def delete(self, habit_id: int) -> bool: ...
    def add_category(self, habit_id: int, category: Category) -> Optional[Habit]: ...
    def remove_category(self, habit_id: int, category: Category) -> Optional[Habit]: ...


class EntryRepository(Protocol):
    def exists_on(self, habit_id: int, d: date) -> bool: ...
    def create(self, habit_id: int, d: date, journal: Optional[str] = None) -> Entry: ...
    def dates_between(self, habit_id: int, start: date, end: date) -> Iterable[date]: ...
    def get_by_date(self, habit_id: int, d: date) -> Optional[Entry]: ...
    def update_journal(self, habit_id: int, d: date, journal: Optional[str]) -> Optional[Entry]: ...
    def list_by_habit(self, habit_id: int) -> List[Entry]: ...


class CategoryRepository(Protocol):
    def create(self, user_id: int, name: str, color: str = "#6366f1") -> Category: ...
    def get(self, category_id: int) -> Optional[Category]: ...
    def list_by_user(self, user_id: int) -> List[Category]: ...
    def exists_name(self, user_id: int, name: str) -> bool: ...
    def update(self, category_id: int, name: Optional[str], color: Optional[str]) -> Optional[Category]: ...
    def delete(self, category_id: int) -> bool: ...
