from collections.abc import Iterable
from datetime import date
from typing import Protocol

from app.models import Entry, Habit


class HabitRepository(Protocol):
    def create(self, user_id: int, name: str, goal_type: str) -> Habit: ...
    def get(self, habit_id: int) -> Habit | None: ...
    def list_by_user(self, user_id: int) -> list[Habit]: ...
    def exists_name(self, user_id: int, name: str) -> bool: ...
    def update(self, habit_id: int, name: str | None, goal_type: str | None) -> Habit | None: ...
    def delete(self, habit_id: int) -> bool: ...

class EntryRepository(Protocol):
    def exists_on(self, habit_id: int, d: date) -> bool: ...
    def create(self, habit_id: int, d: date) -> Entry: ...
    def dates_between(self, habit_id: int, start: date, end: date) -> Iterable[date]: ...
