from collections.abc import Iterable
from datetime import date
from typing import Protocol, Optional, List

from app.models import Category, Entry, Habit


class HabitRepository(Protocol):
    def create(self, user_id: int, name: str, goal_type: str) -> Habit: ...
    def get(self, habit_id: int) -> Optional[Habit]: ...
    def list_by_user(self, user_id: int) -> List[Habit]: ...
    def list_by_user_and_category(self, user_id: int, category_id: int) -> List[Habit]: ...
    def exists_name(self, user_id: int, name: str) -> bool: ...
    def update(self, habit_id: int, name: Optional[str], goal_type: Optional[str]) -> Optional[Habit]: ...
    def delete(self, habit_id: int) -> bool: ...
    def add_category(self, habit_id: int, category: Category) -> Optional[Habit]: ...
    def remove_category(self, habit_id: int, category: Category) -> Optional[Habit]: ...


class EntryRepository(Protocol):
    def exists_on(self, habit_id: int, d: date) -> bool: ...
    def create(self, habit_id: int, d: date) -> Entry: ...
    def dates_between(self, habit_id: int, start: date, end: date) -> Iterable[date]: ...


class CategoryRepository(Protocol):
    def create(self, user_id: int, name: str, color: str = "#6366f1") -> Category: ...
    def get(self, category_id: int) -> Optional[Category]: ...
    def list_by_user(self, user_id: int) -> List[Category]: ...
    def exists_name(self, user_id: int, name: str) -> bool: ...
    def update(self, category_id: int, name: Optional[str], color: Optional[str]) -> Optional[Category]: ...
    def delete(self, category_id: int) -> bool: ...
